#!/usr/bin/groovy
def envStage = "${env.JOB_NAME}-staging"

node {

  git GIT_URL

  stage 'canary release'
    if (!fileExists ('Dockerfile')) {
      writeFile file: 'Dockerfile', text: 'FROM fabric8/swift:2.2-SNAPSHOT-onbuild'
    }

    def newVersion = performCanaryRelease {}

    def rc = getKubernetesJson {
      port = 8080
      label = 'swift'
      icon = 'https://cdn.rawgit.com/fabric8io/fabric8-console/master/img/icons/swift.png'
      version = newVersion
      imageName = clusterImageName
    }

  stage 'Rolling upgrade Staging'
    kubernetesApply(file: rc, environment: envStage)
}
