#!/usr/bin/groovy
hubot room: 'release', message: "release started"
try {

  releaseProject{
    project = 'fabric8-ipaas'
    projectArtifact = 'io/fabric8/ipaas/distro/distro'
  }

  hubot room: 'release', message: "release success"

} catch (err){
    hubot room: 'release', message: "fabric8-ipaas release failed ${err}"
    currentBuild.result = 'FAILURE'
}
